---
- name: Deploy Docker App to Production Server
  hosts: prodserver
  become: yes

  tasks:

    - name: Stop existing container if running
      shell: |
        docker stop php-webapp || true
        docker rm php-webapp || true

    - name: Pull latest image from Jenkins/Test Server (optional)
      shell: docker pull php-webapp:latest
      ignore_errors: yes

    - name: Copy Docker image tar file from Jenkins (if using save/load method)
      copy:
        src: /var/lib/jenkins/workspace/job3_docker/php-webapp.tar
        dest: /tmp/php-webapp.tar
      when: not docker_pull

    - name: Load Docker image (if using tar file)
      shell: docker load -i /tmp/php-webapp.tar
      when: not docker_pull

    - name: Run new container
      shell: |
        docker run -d --name php-webapp -p 80:80 php-webapp:latest
